### ISSUE TITLE
原来wiki.openluat.com的文档是这样生成的

### ISSUE THREAD

**Issue by wendal** [chenxuuu/documentGenerator#1]
看来不是luadoc之类的标准...

**Comment by chenxuuu** [comment]
就是ldoc的标准啊
另外这项目我刚写好，还没有用。。。现在的文档是之前别人人工整理的。。。

**Comment by chenxuuu** [comment]
生成有bug了hhhhh

![image](https://user-images.githubusercontent.com/10357394/54585481-2b430980-4a55-11e9-880d-132c54045166.png)
![image](https://user-images.githubusercontent.com/10357394/54585573-634a4c80-4a55-11e9-8af8-3c2c7e241c59.png)
